### ISSUE TITLE
Error: Plugin loader "python" was not found.

### ISSUE THREAD

**Issue by JuanHdz0** [gmate/gmate#153]
Well, I tried install this plugins before this had a repository in Ubuntu 13.04, I cloned this and I did the manual installation. Now, I installed the repository and updated my system, but I can't activate plugins 'cause appear me that error.

I don't know what I have to do and I'm so newbie in Ubuntu. Also, I hardly understand English. So... I hope You can help me. Thnks.
- Ubuntu 13.04 64-bits
- Gnome 3.8
- GEdit 3
- Rails 3.2.12

**Comment by sayan1999** [comment]
> in /usr/lib/gedit/plugin choice your plugin
> 
> for example gemini.plugin
> 
> Change
> 
> [Plugin]
> Loader = python
> 
> by
> 
> [Plugin]
> Loader = python3
> 
> In some plugins it worked for me

worked for me.
