### ISSUE TITLE
Cannot install on Ubuntu 14.10 Utopic Unicorn

### ISSUE THREAD

**Issue by jefferyto** [gmate/gmate#176]
Two issues:

1.  The PPA (https://launchpad.net/~ubuntu-on-rails/+archive/ubuntu/ppa) hasn't been updated for Utopic.

2.  Trying to install the deb directly leads to conflicts. I force-installed the package and this was the output:

        (Reading database ... 335526 files and directories currently installed.)
        Preparing to unpack gedit-gmate_0.12ppa1_amd64.deb ...
        Unpacking gedit-gmate (0.12ppa1) ...
        dpkg: warning: overriding problem because --force enabled:
        dpkg: warning: trying to overwrite '/usr/share/gtksourceview-3.0/styles/solarized-light.xml', which is also in package libgtksourceview-3.0-common 3.12.3-1ubuntu1
        dpkg: warning: overriding problem because --force enabled:
        dpkg: warning: trying to overwrite '/usr/share/gtksourceview-3.0/styles/solarized-dark.xml', which is also in package libgtksourceview-3.0-common 3.12.3-1ubuntu1
        dpkg: warning: overriding problem because --force enabled:
        dpkg: warning: trying to overwrite '/usr/share/gtksourceview-3.0/language-specs/rst.lang', which is also in package libgtksourceview-3.0-common 3.12.3-1ubuntu1
        Setting up gedit-gmate (0.12ppa1) ...
        Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
        Processing triggers for libglib2.0-0:amd64 (2.42.1-1~ubuntu1) ...
        Processing triggers for libglib2.0-0:i386 (2.42.1-1~ubuntu1) ...

Would be great if this could be fixed - thanks!

**Comment by sigstart** [comment]
Thanks for the heads-up. I'll take a look. The error is probably because the stuff included in Gmate is now already included with Utopic's Gedit package.

**Comment by aurium** [comment]
Same conflict with `solarized-light.xml` in debian, from the same `libgtksourceview-3.0-common` package.

```
dpkg -i gedit-gmate_0.12~uorppa0_amd64.deb
(Reading database ... 271276 files and directories currently installed.)
Preparing to unpack gedit-gmate_0.12~uorppa0_amd64.deb ...
Unpacking gedit-gmate (0.12~uorppa0) ...
dpkg: error processing archive gedit-gmate_0.12~uorppa0_amd64.deb (--install):
 trying to overwrite '/usr/share/gtksourceview-3.0/styles/solarized-light.xml', which is also in package libgtksourceview-3.0-common 3.14.1-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 gedit-gmate_0.12~uorppa0_amd64.deb
```

The `gedit-gmate` package was locally compiled by `apt-src install gedit-gmate`.
