### ISSUE TITLE
ppa for ubuntu xenial Release?

### ISSUE THREAD

**Issue by sijitang** [gmate/gmate#182]
E: Failed to fetch http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found

**Comment by sigstart** [comment]
I haven't upgraded yet, but will see what I can do to get a package in the PPA soon.

**Comment by stanislawworonowicz** [comment]
Have you repair it, yet?

**Comment by TafThorne** [comment]
Looks like there is still and issue with the repository.  

```
$ sudo apt update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
...
Ign:11 http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu xenial InRelease                           
Err:12 http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu xenial Release 
  404  Not Found
Hit:13 http://dist.keybase.io/linux/deb/repo stable InRelease 
Hit:14 http://gb.archive.ubuntu.com/ubuntu xenial InRelease         
Get:15 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:16 http://gb.archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Reading package lists... Done                                  
...
E: The repository 'http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

With out a release file I do not seem able to install this package on Ubuntu 16.04.  Looking at the URL in a browser it seems that the whole xenial Release may be missing.

**Comment by sigstart** [comment]
Sorry this took so long. I didn't have an Ubuntu install anymore. I've set up some virtual machines now that will help me maintain this in future releases. Will be adding packages for Yakkety and Zesty soon.
