### ISSUE TITLE
Cannot add ppa on Ubuntu 18.04

### ISSUE THREAD

**Issue by xuwangly** [gmate/gmate#185]
I want to install Gmate in my computer(Ubuntu 18.04).
Then i need to add the ppa , and it gone wrong:

sudo apt-add-repository ppa:ubuntu-on-rails/ppa

The error log show:

错误:11 http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
错误:12 http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu bionic Release                              
  404  Not Found [IP: 91.189.95.83 80]
...
E: 仓库 “http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu bionic Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。

**Comment by sigstart** [comment]
Thanks for the report. As stated in a previous report, I don't really use Ubuntu as my desktop OS anymore, but I'll get it going in Virtual Box and see what I can do about updating the PPA.
