### ISSUE TITLE
TextMap for gedit3

### ISSUE THREAD

**Issue by Celestial-intelligence** [gmate/gmate#186]
really missing that plugin now..if there are ways to reimplement it..?

**Comment by Celestial-intelligence** [comment]
gedit in ubuntu now uses python 3 .. I tried using 2to3 and
the plugin seems to run, but nothing in the textmap is empty and there are couple of errors.

To get it working in python 3, with 2to3:

In textmap.plugin change the loader:

Loader=python3

Run 2to3 on textmap.py

2to3 -w textmap.py 

Install as normal.

also check this https://github.com/ddev/textmap/pull/1/files

**Comment by sigstart** [comment]
I'll spend a few hours on this today and see if I can get the PPA working again, and test these gedit3 ports for TextMap.

**Comment by Celestial-intelligence** [comment]
thank you!

**Comment by sigstart** [comment]
The contributor to that Python3 port of the TextMap plugin (@aeischeid) posted a comment on one of the issues in this repo (#65 --- [permalink](https://github.com/gmate/gmate/issues/65#issuecomment-9341751)).

They asked back then for someone to help them finish the port. So I'm going to try your 2to3 method and see how that goes first.

**Comment by Celestial-intelligence** [comment]
hey! need any help?

**Comment by sigstart** [comment]
My country went into lockdown due to COVID-19 in the week after I last posted. As a result, I have been working almost non-stop (I am one of those fortunate enough to be able to work from home).

I'll make some time in this week to check in what I was able to do, and then we'll take it from there.

**Comment by sigstart** [comment]
So while trying to get the TextMap plugin to work in gedit3, I noticed that there is already setting in Gedit in Ubuntu 18.04 (Gedit 3.28.1) called "Display overview map".

![Gedit Preferences dialog](https://user-images.githubusercontent.com/2140394/78988286-d4611400-7b30-11ea-8b83-71baf8819583.png)

Is there something that TextMap did that the built-in overview map doesn't do?

**Comment by Celestial-intelligence** [comment]
have no this menu item in Debian Buster with Gnome as DE

**Comment by sigstart** [comment]
Just did an install of Debian Buster (10.3) in a VM and found the menu option.

Click on "Text Editor" in the title bar, then select "Preferences":

![image](https://user-images.githubusercontent.com/2140394/79446452-863f8b00-7fde-11ea-9efe-dcb10aac5b72.png)

Then click on the "Display overview map" option in the Preferences pane:

![image](https://user-images.githubusercontent.com/2140394/79446390-6f009d80-7fde-11ea-9aac-0047e5c0eafd.png)

If you don't see it, try updating Gedit. I'm not sure in which version the overview map was added.

**Comment by Celestial-intelligence** [comment]
ohh yeap, now i see that. thnx a lot!
